services:
  backend:
    build: ../backend/
    container_name: aosr-back
    networks:
      - app-network
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ../frontend/
    container_name: aosr-front
    networks:
      - app-network
    ports:
      - "80:5173"
    depends_on:
      - backend

  db:
    image: postgres:17
    restart: always
    networks:
      - app-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

  db_backup:
    build: ./backup
    depends_on:
      - db
    restart: always
    networks:
      - app-network
    environment:
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGDATABASE: ${POSTGRES_DB}
      PGHOST: db
    volumes:
      - pg_backups:/backups

volumes:
  db_data:
  pg_backups:

networks:
  app-network:
    external: true
